/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL.impl;

import adrf.xtext.typoDSL.Blocks;
import adrf.xtext.typoDSL.TypoDSLPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Blocks</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BlocksImpl extends MinimalEObjectImpl.Container implements Blocks
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BlocksImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TypoDSLPackage.Literals.BLOCKS;
  }

} //BlocksImpl
