/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL.impl;

import adrf.xtext.typoDSL.Blocks;
import adrf.xtext.typoDSL.Document;
import adrf.xtext.typoDSL.TypoDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.impl.DocumentImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.impl.DocumentImpl#getAuthor <em>Author</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.impl.DocumentImpl#getDatetime <em>Datetime</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.impl.DocumentImpl#getTldr <em>Tldr</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.impl.DocumentImpl#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DocumentImpl extends MinimalEObjectImpl.Container implements Document
{
  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getAuthor() <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthor()
   * @generated
   * @ordered
   */
  protected static final String AUTHOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAuthor() <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthor()
   * @generated
   * @ordered
   */
  protected String author = AUTHOR_EDEFAULT;

  /**
   * The default value of the '{@link #getDatetime() <em>Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDatetime()
   * @generated
   * @ordered
   */
  protected static final String DATETIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDatetime() <em>Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDatetime()
   * @generated
   * @ordered
   */
  protected String datetime = DATETIME_EDEFAULT;

  /**
   * The default value of the '{@link #getTldr() <em>Tldr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTldr()
   * @generated
   * @ordered
   */
  protected static final String TLDR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTldr() <em>Tldr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTldr()
   * @generated
   * @ordered
   */
  protected String tldr = TLDR_EDEFAULT;

  /**
   * The cached value of the '{@link #getBlocks() <em>Blocks</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBlocks()
   * @generated
   * @ordered
   */
  protected EList<Blocks> blocks;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DocumentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TypoDSLPackage.Literals.DOCUMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TypoDSLPackage.DOCUMENT__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAuthor()
  {
    return author;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAuthor(String newAuthor)
  {
    String oldAuthor = author;
    author = newAuthor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TypoDSLPackage.DOCUMENT__AUTHOR, oldAuthor, author));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDatetime()
  {
    return datetime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDatetime(String newDatetime)
  {
    String oldDatetime = datetime;
    datetime = newDatetime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TypoDSLPackage.DOCUMENT__DATETIME, oldDatetime, datetime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTldr()
  {
    return tldr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTldr(String newTldr)
  {
    String oldTldr = tldr;
    tldr = newTldr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TypoDSLPackage.DOCUMENT__TLDR, oldTldr, tldr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Blocks> getBlocks()
  {
    if (blocks == null)
    {
      blocks = new EObjectContainmentEList<Blocks>(Blocks.class, this, TypoDSLPackage.DOCUMENT__BLOCKS);
    }
    return blocks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TypoDSLPackage.DOCUMENT__BLOCKS:
        return ((InternalEList<?>)getBlocks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TypoDSLPackage.DOCUMENT__TITLE:
        return getTitle();
      case TypoDSLPackage.DOCUMENT__AUTHOR:
        return getAuthor();
      case TypoDSLPackage.DOCUMENT__DATETIME:
        return getDatetime();
      case TypoDSLPackage.DOCUMENT__TLDR:
        return getTldr();
      case TypoDSLPackage.DOCUMENT__BLOCKS:
        return getBlocks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TypoDSLPackage.DOCUMENT__TITLE:
        setTitle((String)newValue);
        return;
      case TypoDSLPackage.DOCUMENT__AUTHOR:
        setAuthor((String)newValue);
        return;
      case TypoDSLPackage.DOCUMENT__DATETIME:
        setDatetime((String)newValue);
        return;
      case TypoDSLPackage.DOCUMENT__TLDR:
        setTldr((String)newValue);
        return;
      case TypoDSLPackage.DOCUMENT__BLOCKS:
        getBlocks().clear();
        getBlocks().addAll((Collection<? extends Blocks>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TypoDSLPackage.DOCUMENT__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case TypoDSLPackage.DOCUMENT__AUTHOR:
        setAuthor(AUTHOR_EDEFAULT);
        return;
      case TypoDSLPackage.DOCUMENT__DATETIME:
        setDatetime(DATETIME_EDEFAULT);
        return;
      case TypoDSLPackage.DOCUMENT__TLDR:
        setTldr(TLDR_EDEFAULT);
        return;
      case TypoDSLPackage.DOCUMENT__BLOCKS:
        getBlocks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TypoDSLPackage.DOCUMENT__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case TypoDSLPackage.DOCUMENT__AUTHOR:
        return AUTHOR_EDEFAULT == null ? author != null : !AUTHOR_EDEFAULT.equals(author);
      case TypoDSLPackage.DOCUMENT__DATETIME:
        return DATETIME_EDEFAULT == null ? datetime != null : !DATETIME_EDEFAULT.equals(datetime);
      case TypoDSLPackage.DOCUMENT__TLDR:
        return TLDR_EDEFAULT == null ? tldr != null : !TLDR_EDEFAULT.equals(tldr);
      case TypoDSLPackage.DOCUMENT__BLOCKS:
        return blocks != null && !blocks.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (title: ");
    result.append(title);
    result.append(", author: ");
    result.append(author);
    result.append(", datetime: ");
    result.append(datetime);
    result.append(", tldr: ");
    result.append(tldr);
    result.append(')');
    return result.toString();
  }

} //DocumentImpl
