/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL.impl;

import adrf.xtext.typoDSL.Italic;
import adrf.xtext.typoDSL.TypoDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Italic</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ItalicImpl extends InlineItemImpl implements Italic
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ItalicImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TypoDSLPackage.Literals.ITALIC;
  }

} //ItalicImpl
