/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL.impl;

import adrf.xtext.typoDSL.Normal;
import adrf.xtext.typoDSL.TypoDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Normal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NormalImpl extends InlineItemImpl implements Normal
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NormalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TypoDSLPackage.Literals.NORMAL;
  }

} //NormalImpl
