/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL.impl;

import adrf.xtext.typoDSL.InlineItem;
import adrf.xtext.typoDSL.Paragraph;
import adrf.xtext.typoDSL.TypoDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Paragraph</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.impl.ParagraphImpl#getInlineitems <em>Inlineitems</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParagraphImpl extends BlocksImpl implements Paragraph
{
  /**
   * The cached value of the '{@link #getInlineitems() <em>Inlineitems</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInlineitems()
   * @generated
   * @ordered
   */
  protected EList<InlineItem> inlineitems;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParagraphImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TypoDSLPackage.Literals.PARAGRAPH;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InlineItem> getInlineitems()
  {
    if (inlineitems == null)
    {
      inlineitems = new EObjectContainmentEList<InlineItem>(InlineItem.class, this, TypoDSLPackage.PARAGRAPH__INLINEITEMS);
    }
    return inlineitems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TypoDSLPackage.PARAGRAPH__INLINEITEMS:
        return ((InternalEList<?>)getInlineitems()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TypoDSLPackage.PARAGRAPH__INLINEITEMS:
        return getInlineitems();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TypoDSLPackage.PARAGRAPH__INLINEITEMS:
        getInlineitems().clear();
        getInlineitems().addAll((Collection<? extends InlineItem>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TypoDSLPackage.PARAGRAPH__INLINEITEMS:
        getInlineitems().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TypoDSLPackage.PARAGRAPH__INLINEITEMS:
        return inlineitems != null && !inlineitems.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ParagraphImpl
