/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL.impl;

import adrf.xtext.typoDSL.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TypoDSLFactoryImpl extends EFactoryImpl implements TypoDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TypoDSLFactory init()
  {
    try
    {
      TypoDSLFactory theTypoDSLFactory = (TypoDSLFactory)EPackage.Registry.INSTANCE.getEFactory(TypoDSLPackage.eNS_URI);
      if (theTypoDSLFactory != null)
      {
        return theTypoDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TypoDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypoDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TypoDSLPackage.DOCUMENT: return createDocument();
      case TypoDSLPackage.BLOCKS: return createBlocks();
      case TypoDSLPackage.SECTION: return createSection();
      case TypoDSLPackage.SUBSECTION: return createSubsection();
      case TypoDSLPackage.PARAGRAPH: return createParagraph();
      case TypoDSLPackage.IMAGE: return createImage();
      case TypoDSLPackage.CODE_BLOCK: return createCodeBlock();
      case TypoDSLPackage.ITEMIZE: return createItemize();
      case TypoDSLPackage.LIST_ITEM: return createListItem();
      case TypoDSLPackage.INLINE_ITEM: return createInlineItem();
      case TypoDSLPackage.NORMAL: return createNormal();
      case TypoDSLPackage.BOLD: return createBold();
      case TypoDSLPackage.ITALIC: return createItalic();
      case TypoDSLPackage.LINK: return createLink();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Document createDocument()
  {
    DocumentImpl document = new DocumentImpl();
    return document;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Blocks createBlocks()
  {
    BlocksImpl blocks = new BlocksImpl();
    return blocks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Section createSection()
  {
    SectionImpl section = new SectionImpl();
    return section;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Subsection createSubsection()
  {
    SubsectionImpl subsection = new SubsectionImpl();
    return subsection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Paragraph createParagraph()
  {
    ParagraphImpl paragraph = new ParagraphImpl();
    return paragraph;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Image createImage()
  {
    ImageImpl image = new ImageImpl();
    return image;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CodeBlock createCodeBlock()
  {
    CodeBlockImpl codeBlock = new CodeBlockImpl();
    return codeBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Itemize createItemize()
  {
    ItemizeImpl itemize = new ItemizeImpl();
    return itemize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ListItem createListItem()
  {
    ListItemImpl listItem = new ListItemImpl();
    return listItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InlineItem createInlineItem()
  {
    InlineItemImpl inlineItem = new InlineItemImpl();
    return inlineItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Normal createNormal()
  {
    NormalImpl normal = new NormalImpl();
    return normal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bold createBold()
  {
    BoldImpl bold = new BoldImpl();
    return bold;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Italic createItalic()
  {
    ItalicImpl italic = new ItalicImpl();
    return italic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Link createLink()
  {
    LinkImpl link = new LinkImpl();
    return link;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypoDSLPackage getTypoDSLPackage()
  {
    return (TypoDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TypoDSLPackage getPackage()
  {
    return TypoDSLPackage.eINSTANCE;
  }

} //TypoDSLFactoryImpl
