/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.ide;

import adrf.xtext.TypoDSLRuntimeModule;
import adrf.xtext.TypoDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TypoDSLIdeSetup extends TypoDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TypoDSLRuntimeModule(), new TypoDSLIdeModule()));
	}
	
}
