/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.ui.tests;

import adrf.xtext.typo.ui.internal.TypoActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TypoDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TypoActivator.getInstance().getInjector("adrf.xtext.TypoDSL");
	}

}
