/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.ui;

import adrf.xtext.typo.ui.internal.TypoActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TypoDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TypoActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TypoActivator activator = TypoActivator.getInstance();
		return activator != null ? activator.getInjector(TypoActivator.ADRF_XTEXT_TYPODSL) : null;
	}

}
