/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTypoDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(adrf.xtext.typoDSL.TypoDSLPackage.eINSTANCE);
		return result;
	}
}
