/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TypoDSLUiModule extends AbstractTypoDSLUiModule {

	public TypoDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
