/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.parser.antlr;

import adrf.xtext.parser.antlr.internal.InternalTypoDSLParser;
import adrf.xtext.services.TypoDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TypoDSLParser extends AbstractAntlrParser {

	@Inject
	private TypoDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTypoDSLParser createParser(XtextTokenStream stream) {
		return new InternalTypoDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}

	public TypoDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TypoDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
