/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Blocks</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getBlocks()
 * @model
 * @generated
 */
public interface Blocks extends EObject
{
} // Blocks
