/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bold</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getBold()
 * @model
 * @generated
 */
public interface Bold extends InlineItem
{
} // Bold
