/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.Document#getTitle <em>Title</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Document#getAuthor <em>Author</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Document#getDatetime <em>Datetime</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Document#getTldr <em>Tldr</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Document#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getDocument_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Document#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Author</em>' attribute.
   * @see #setAuthor(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getDocument_Author()
   * @model
   * @generated
   */
  String getAuthor();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Document#getAuthor <em>Author</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Author</em>' attribute.
   * @see #getAuthor()
   * @generated
   */
  void setAuthor(String value);

  /**
   * Returns the value of the '<em><b>Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datetime</em>' attribute.
   * @see #setDatetime(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getDocument_Datetime()
   * @model
   * @generated
   */
  String getDatetime();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Document#getDatetime <em>Datetime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datetime</em>' attribute.
   * @see #getDatetime()
   * @generated
   */
  void setDatetime(String value);

  /**
   * Returns the value of the '<em><b>Tldr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tldr</em>' attribute.
   * @see #setTldr(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getDocument_Tldr()
   * @model
   * @generated
   */
  String getTldr();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Document#getTldr <em>Tldr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tldr</em>' attribute.
   * @see #getTldr()
   * @generated
   */
  void setTldr(String value);

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link adrf.xtext.typoDSL.Blocks}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getDocument_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<Blocks> getBlocks();

} // Document
