/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.Image#getUrl <em>Url</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Image#getWidth <em>Width</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Image#getHeight <em>Height</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Image#getCaption <em>Caption</em>}</li>
 * </ul>
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getImage()
 * @model
 * @generated
 */
public interface Image extends Blocks
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getImage_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Image#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Width</em>' attribute.
   * @see #setWidth(int)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getImage_Width()
   * @model
   * @generated
   */
  int getWidth();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Image#getWidth <em>Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Width</em>' attribute.
   * @see #getWidth()
   * @generated
   */
  void setWidth(int value);

  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(int)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getImage_Height()
   * @model
   * @generated
   */
  int getHeight();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Image#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(int value);

  /**
   * Returns the value of the '<em><b>Caption</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Caption</em>' attribute.
   * @see #setCaption(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getImage_Caption()
   * @model
   * @generated
   */
  String getCaption();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Image#getCaption <em>Caption</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Caption</em>' attribute.
   * @see #getCaption()
   * @generated
   */
  void setCaption(String value);

} // Image
