/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Itemize</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.Itemize#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getItemize()
 * @model
 * @generated
 */
public interface Itemize extends Blocks
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link adrf.xtext.typoDSL.ListItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getItemize_Items()
   * @model containment="true"
   * @generated
   */
  EList<ListItem> getItems();

} // Itemize
