/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.Link#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getLink()
 * @model
 * @generated
 */
public interface Link extends InlineItem
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getLink_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Link#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

} // Link
