/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getNormal()
 * @model
 * @generated
 */
public interface Normal extends InlineItem
{
} // Normal
