/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paragraph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.Paragraph#getInlineitems <em>Inlineitems</em>}</li>
 * </ul>
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getParagraph()
 * @model
 * @generated
 */
public interface Paragraph extends Blocks
{
  /**
   * Returns the value of the '<em><b>Inlineitems</b></em>' containment reference list.
   * The list contents are of type {@link adrf.xtext.typoDSL.InlineItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inlineitems</em>' containment reference list.
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getParagraph_Inlineitems()
   * @model containment="true"
   * @generated
   */
  EList<InlineItem> getInlineitems();

} // Paragraph
