/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subsection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link adrf.xtext.typoDSL.Subsection#getTitle <em>Title</em>}</li>
 *   <li>{@link adrf.xtext.typoDSL.Subsection#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see adrf.xtext.typoDSL.TypoDSLPackage#getSubsection()
 * @model
 * @generated
 */
public interface Subsection extends Blocks
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getSubsection_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link adrf.xtext.typoDSL.Subsection#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link adrf.xtext.typoDSL.Blocks}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see adrf.xtext.typoDSL.TypoDSLPackage#getSubsection_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<Blocks> getBlocks();

} // Subsection
