/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.typoDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see adrf.xtext.typoDSL.TypoDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TypoDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "typoDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.adrf/TypoDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "typoDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TypoDSLPackage eINSTANCE = adrf.xtext.typoDSL.impl.TypoDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.DocumentImpl <em>Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.DocumentImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getDocument()
   * @generated
   */
  int DOCUMENT = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__TITLE = 0;

  /**
   * The feature id for the '<em><b>Author</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__AUTHOR = 1;

  /**
   * The feature id for the '<em><b>Datetime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__DATETIME = 2;

  /**
   * The feature id for the '<em><b>Tldr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__TLDR = 3;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__BLOCKS = 4;

  /**
   * The number of structural features of the '<em>Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.BlocksImpl <em>Blocks</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.BlocksImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getBlocks()
   * @generated
   */
  int BLOCKS = 1;

  /**
   * The number of structural features of the '<em>Blocks</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCKS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.SectionImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getSection()
   * @generated
   */
  int SECTION = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__TITLE = BLOCKS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__BLOCKS = BLOCKS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = BLOCKS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.SubsectionImpl <em>Subsection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.SubsectionImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getSubsection()
   * @generated
   */
  int SUBSECTION = 3;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSECTION__TITLE = BLOCKS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSECTION__BLOCKS = BLOCKS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Subsection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSECTION_FEATURE_COUNT = BLOCKS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.ParagraphImpl <em>Paragraph</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.ParagraphImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getParagraph()
   * @generated
   */
  int PARAGRAPH = 4;

  /**
   * The feature id for the '<em><b>Inlineitems</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAPH__INLINEITEMS = BLOCKS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Paragraph</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAPH_FEATURE_COUNT = BLOCKS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.ImageImpl <em>Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.ImageImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getImage()
   * @generated
   */
  int IMAGE = 5;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__URL = BLOCKS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__WIDTH = BLOCKS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__HEIGHT = BLOCKS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Caption</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE__CAPTION = BLOCKS_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_FEATURE_COUNT = BLOCKS_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.CodeBlockImpl <em>Code Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.CodeBlockImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getCodeBlock()
   * @generated
   */
  int CODE_BLOCK = 6;

  /**
   * The feature id for the '<em><b>Language</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_BLOCK__LANGUAGE = BLOCKS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_BLOCK__TEXT = BLOCKS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Code Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_BLOCK_FEATURE_COUNT = BLOCKS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.ItemizeImpl <em>Itemize</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.ItemizeImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getItemize()
   * @generated
   */
  int ITEMIZE = 7;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEMIZE__ITEMS = BLOCKS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Itemize</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEMIZE_FEATURE_COUNT = BLOCKS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.ListItemImpl <em>List Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.ListItemImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getListItem()
   * @generated
   */
  int LIST_ITEM = 8;

  /**
   * The feature id for the '<em><b>Inline</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ITEM__INLINE = 0;

  /**
   * The number of structural features of the '<em>List Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.InlineItemImpl <em>Inline Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.InlineItemImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getInlineItem()
   * @generated
   */
  int INLINE_ITEM = 9;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INLINE_ITEM__TEXT = 0;

  /**
   * The number of structural features of the '<em>Inline Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INLINE_ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.NormalImpl <em>Normal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.NormalImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getNormal()
   * @generated
   */
  int NORMAL = 10;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL__TEXT = INLINE_ITEM__TEXT;

  /**
   * The number of structural features of the '<em>Normal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_FEATURE_COUNT = INLINE_ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.BoldImpl <em>Bold</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.BoldImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getBold()
   * @generated
   */
  int BOLD = 11;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOLD__TEXT = INLINE_ITEM__TEXT;

  /**
   * The number of structural features of the '<em>Bold</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOLD_FEATURE_COUNT = INLINE_ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.ItalicImpl <em>Italic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.ItalicImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getItalic()
   * @generated
   */
  int ITALIC = 12;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITALIC__TEXT = INLINE_ITEM__TEXT;

  /**
   * The number of structural features of the '<em>Italic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITALIC_FEATURE_COUNT = INLINE_ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link adrf.xtext.typoDSL.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see adrf.xtext.typoDSL.impl.LinkImpl
   * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getLink()
   * @generated
   */
  int LINK = 13;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__TEXT = INLINE_ITEM__TEXT;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__URL = INLINE_ITEM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = INLINE_ITEM_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Document <em>Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Document</em>'.
   * @see adrf.xtext.typoDSL.Document
   * @generated
   */
  EClass getDocument();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Document#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see adrf.xtext.typoDSL.Document#getTitle()
   * @see #getDocument()
   * @generated
   */
  EAttribute getDocument_Title();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Document#getAuthor <em>Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Author</em>'.
   * @see adrf.xtext.typoDSL.Document#getAuthor()
   * @see #getDocument()
   * @generated
   */
  EAttribute getDocument_Author();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Document#getDatetime <em>Datetime</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datetime</em>'.
   * @see adrf.xtext.typoDSL.Document#getDatetime()
   * @see #getDocument()
   * @generated
   */
  EAttribute getDocument_Datetime();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Document#getTldr <em>Tldr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tldr</em>'.
   * @see adrf.xtext.typoDSL.Document#getTldr()
   * @see #getDocument()
   * @generated
   */
  EAttribute getDocument_Tldr();

  /**
   * Returns the meta object for the containment reference list '{@link adrf.xtext.typoDSL.Document#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see adrf.xtext.typoDSL.Document#getBlocks()
   * @see #getDocument()
   * @generated
   */
  EReference getDocument_Blocks();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Blocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blocks</em>'.
   * @see adrf.xtext.typoDSL.Blocks
   * @generated
   */
  EClass getBlocks();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see adrf.xtext.typoDSL.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Section#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see adrf.xtext.typoDSL.Section#getTitle()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_Title();

  /**
   * Returns the meta object for the containment reference list '{@link adrf.xtext.typoDSL.Section#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see adrf.xtext.typoDSL.Section#getBlocks()
   * @see #getSection()
   * @generated
   */
  EReference getSection_Blocks();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Subsection <em>Subsection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subsection</em>'.
   * @see adrf.xtext.typoDSL.Subsection
   * @generated
   */
  EClass getSubsection();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Subsection#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see adrf.xtext.typoDSL.Subsection#getTitle()
   * @see #getSubsection()
   * @generated
   */
  EAttribute getSubsection_Title();

  /**
   * Returns the meta object for the containment reference list '{@link adrf.xtext.typoDSL.Subsection#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see adrf.xtext.typoDSL.Subsection#getBlocks()
   * @see #getSubsection()
   * @generated
   */
  EReference getSubsection_Blocks();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Paragraph <em>Paragraph</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paragraph</em>'.
   * @see adrf.xtext.typoDSL.Paragraph
   * @generated
   */
  EClass getParagraph();

  /**
   * Returns the meta object for the containment reference list '{@link adrf.xtext.typoDSL.Paragraph#getInlineitems <em>Inlineitems</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inlineitems</em>'.
   * @see adrf.xtext.typoDSL.Paragraph#getInlineitems()
   * @see #getParagraph()
   * @generated
   */
  EReference getParagraph_Inlineitems();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Image <em>Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image</em>'.
   * @see adrf.xtext.typoDSL.Image
   * @generated
   */
  EClass getImage();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Image#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see adrf.xtext.typoDSL.Image#getUrl()
   * @see #getImage()
   * @generated
   */
  EAttribute getImage_Url();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Image#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see adrf.xtext.typoDSL.Image#getWidth()
   * @see #getImage()
   * @generated
   */
  EAttribute getImage_Width();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Image#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see adrf.xtext.typoDSL.Image#getHeight()
   * @see #getImage()
   * @generated
   */
  EAttribute getImage_Height();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Image#getCaption <em>Caption</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Caption</em>'.
   * @see adrf.xtext.typoDSL.Image#getCaption()
   * @see #getImage()
   * @generated
   */
  EAttribute getImage_Caption();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.CodeBlock <em>Code Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Code Block</em>'.
   * @see adrf.xtext.typoDSL.CodeBlock
   * @generated
   */
  EClass getCodeBlock();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.CodeBlock#getLanguage <em>Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Language</em>'.
   * @see adrf.xtext.typoDSL.CodeBlock#getLanguage()
   * @see #getCodeBlock()
   * @generated
   */
  EAttribute getCodeBlock_Language();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.CodeBlock#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see adrf.xtext.typoDSL.CodeBlock#getText()
   * @see #getCodeBlock()
   * @generated
   */
  EAttribute getCodeBlock_Text();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Itemize <em>Itemize</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Itemize</em>'.
   * @see adrf.xtext.typoDSL.Itemize
   * @generated
   */
  EClass getItemize();

  /**
   * Returns the meta object for the containment reference list '{@link adrf.xtext.typoDSL.Itemize#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see adrf.xtext.typoDSL.Itemize#getItems()
   * @see #getItemize()
   * @generated
   */
  EReference getItemize_Items();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.ListItem <em>List Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Item</em>'.
   * @see adrf.xtext.typoDSL.ListItem
   * @generated
   */
  EClass getListItem();

  /**
   * Returns the meta object for the containment reference list '{@link adrf.xtext.typoDSL.ListItem#getInline <em>Inline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inline</em>'.
   * @see adrf.xtext.typoDSL.ListItem#getInline()
   * @see #getListItem()
   * @generated
   */
  EReference getListItem_Inline();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.InlineItem <em>Inline Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inline Item</em>'.
   * @see adrf.xtext.typoDSL.InlineItem
   * @generated
   */
  EClass getInlineItem();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.InlineItem#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see adrf.xtext.typoDSL.InlineItem#getText()
   * @see #getInlineItem()
   * @generated
   */
  EAttribute getInlineItem_Text();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Normal <em>Normal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal</em>'.
   * @see adrf.xtext.typoDSL.Normal
   * @generated
   */
  EClass getNormal();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Bold <em>Bold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bold</em>'.
   * @see adrf.xtext.typoDSL.Bold
   * @generated
   */
  EClass getBold();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Italic <em>Italic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Italic</em>'.
   * @see adrf.xtext.typoDSL.Italic
   * @generated
   */
  EClass getItalic();

  /**
   * Returns the meta object for class '{@link adrf.xtext.typoDSL.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see adrf.xtext.typoDSL.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the attribute '{@link adrf.xtext.typoDSL.Link#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see adrf.xtext.typoDSL.Link#getUrl()
   * @see #getLink()
   * @generated
   */
  EAttribute getLink_Url();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TypoDSLFactory getTypoDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.DocumentImpl <em>Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.DocumentImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getDocument()
     * @generated
     */
    EClass DOCUMENT = eINSTANCE.getDocument();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCUMENT__TITLE = eINSTANCE.getDocument_Title();

    /**
     * The meta object literal for the '<em><b>Author</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCUMENT__AUTHOR = eINSTANCE.getDocument_Author();

    /**
     * The meta object literal for the '<em><b>Datetime</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCUMENT__DATETIME = eINSTANCE.getDocument_Datetime();

    /**
     * The meta object literal for the '<em><b>Tldr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOCUMENT__TLDR = eINSTANCE.getDocument_Tldr();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCUMENT__BLOCKS = eINSTANCE.getDocument_Blocks();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.BlocksImpl <em>Blocks</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.BlocksImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getBlocks()
     * @generated
     */
    EClass BLOCKS = eINSTANCE.getBlocks();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.SectionImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__TITLE = eINSTANCE.getSection_Title();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECTION__BLOCKS = eINSTANCE.getSection_Blocks();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.SubsectionImpl <em>Subsection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.SubsectionImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getSubsection()
     * @generated
     */
    EClass SUBSECTION = eINSTANCE.getSubsection();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBSECTION__TITLE = eINSTANCE.getSubsection_Title();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBSECTION__BLOCKS = eINSTANCE.getSubsection_Blocks();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.ParagraphImpl <em>Paragraph</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.ParagraphImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getParagraph()
     * @generated
     */
    EClass PARAGRAPH = eINSTANCE.getParagraph();

    /**
     * The meta object literal for the '<em><b>Inlineitems</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAGRAPH__INLINEITEMS = eINSTANCE.getParagraph_Inlineitems();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.ImageImpl <em>Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.ImageImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getImage()
     * @generated
     */
    EClass IMAGE = eINSTANCE.getImage();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__URL = eINSTANCE.getImage_Url();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__WIDTH = eINSTANCE.getImage_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__HEIGHT = eINSTANCE.getImage_Height();

    /**
     * The meta object literal for the '<em><b>Caption</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE__CAPTION = eINSTANCE.getImage_Caption();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.CodeBlockImpl <em>Code Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.CodeBlockImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getCodeBlock()
     * @generated
     */
    EClass CODE_BLOCK = eINSTANCE.getCodeBlock();

    /**
     * The meta object literal for the '<em><b>Language</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODE_BLOCK__LANGUAGE = eINSTANCE.getCodeBlock_Language();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODE_BLOCK__TEXT = eINSTANCE.getCodeBlock_Text();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.ItemizeImpl <em>Itemize</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.ItemizeImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getItemize()
     * @generated
     */
    EClass ITEMIZE = eINSTANCE.getItemize();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEMIZE__ITEMS = eINSTANCE.getItemize_Items();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.ListItemImpl <em>List Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.ListItemImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getListItem()
     * @generated
     */
    EClass LIST_ITEM = eINSTANCE.getListItem();

    /**
     * The meta object literal for the '<em><b>Inline</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_ITEM__INLINE = eINSTANCE.getListItem_Inline();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.InlineItemImpl <em>Inline Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.InlineItemImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getInlineItem()
     * @generated
     */
    EClass INLINE_ITEM = eINSTANCE.getInlineItem();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INLINE_ITEM__TEXT = eINSTANCE.getInlineItem_Text();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.NormalImpl <em>Normal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.NormalImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getNormal()
     * @generated
     */
    EClass NORMAL = eINSTANCE.getNormal();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.BoldImpl <em>Bold</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.BoldImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getBold()
     * @generated
     */
    EClass BOLD = eINSTANCE.getBold();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.ItalicImpl <em>Italic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.ItalicImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getItalic()
     * @generated
     */
    EClass ITALIC = eINSTANCE.getItalic();

    /**
     * The meta object literal for the '{@link adrf.xtext.typoDSL.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see adrf.xtext.typoDSL.impl.LinkImpl
     * @see adrf.xtext.typoDSL.impl.TypoDSLPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINK__URL = eINSTANCE.getLink_Url();

  }

} //TypoDSLPackage
