/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TypoDSLStandaloneSetup extends TypoDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new TypoDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
