/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TypoDSLRuntimeModule extends AbstractTypoDSLRuntimeModule {
}

