/*
 * generated by Xtext 2.30.0
 */
package adrf.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTypoDSLScopeProvider extends DelegatingScopeProvider {
}
