/**
 * generated by Xtext 2.30.0
 */
package adrf.xtext.generator;

import javax.inject.Inject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class TypoDSLGenerator extends AbstractGenerator {
  @Inject
  private TypoMDGenerator mdGen;

  @Inject
  private TypoTexGenerator texGen;

  @Inject
  private TypoHTMLGenerator htmlGen;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    this.mdGen.doGenerate(resource, fsa, context);
    this.texGen.doGenerate(resource, fsa, context);
    this.htmlGen.doGenerate(resource, fsa, context);
  }
}
